### ISSUE TITLE
DOCS: ISSUE and PR templates

### ISSUE THREAD

**Issue by Vyvy-vi** [Heptagram-Bot/api#4]
## Description-
It would be really useful if we can set up ISSUE templates and PR templates, since that facilitates better communication, and thus helps people that want to contribute to the project.

**Comment by j-dogcoder** [comment]
I could do that. Anything in particular you want? My thought would be to use the templates from the Heptagram repo again unless you have something else in mind.

**Comment by j-dogcoder** [comment]
Also, what do you think about the labels @Vyvy-vi? Currently it just has the defaults, but we could use an action or change up the labels if you'd like.

**Comment by Vyvy-vi** [comment]
Hmm, we can do the custom labels from Heptagram's repo

**Comment by Vyvy-vi** [comment]
> I could do that. Anything in particular you want? My thought would be to use the templates from the Heptagram repo again unless you have something else in mind.

Sure!

**Comment by Vyvy-vi** [comment]
Try doing this in a new branch and open a PR though. (wouldn't want weird untracked branches)

**Comment by j-dogcoder** [comment]
Are we using the existing things?

**Comment by Vyvy-vi** [comment]
Yes, I think the existing stuff would make more conventional sense

**Comment by Vyvy-vi** [comment]
(We might need to update the labels though)

**Comment by MidouWebDev** [comment]
@Vyvy-vi i will add them

**Comment by j-dogcoder** [comment]
I think we already have them?

**Comment by j-dogcoder** [comment]
Look @MidouWebDev Want to add the ones from the bot repo?

**Comment by MidouWebDev** [comment]
@j-dogcoder i habe an other example i created for another open source project if you want me to add yours lemme know

**Comment by MidouWebDev** [comment]
@j-dogcoder i am going to add them right now :wink:

**Comment by Vyvy-vi** [comment]
That PR was merged in a staging branch 😅

**Comment by j-dogcoder** [comment]
Woops!
