### ISSUE TITLE
CHORE(ci): Set up github actions

### ISSUE THREAD

**Issue by Vyvy-vi** [Heptagram-Bot/api#5]
## Description-
GIthub actions would make the dev-workflow smoother.

The following actions might be added here-
- Linter + Formatter
- Test runner
- Automatic Releases + Changelog
- Docker Image Pusher (to github registry)
- CodeQL

**Comment by j-dogcoder** [comment]
Github actions isn't really my speed, but I can for sure do other things. 😄

**Comment by Vyvy-vi** [comment]
np, I'll set it up :)
